version: '3.1'

services:
  nginx:
    build: ./nginx
    ports:
      - '80:80'
  db:
    build: ./mongo
    restart: always
    volumes:
      - ./mongo/data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME_FILE: /run/secrets/mongo_root_user
      MONGO_INITDB_ROOT_PASSWORD_FILE: /run/secrets/mongo_root_pass
      MONGO_INITDB_DATABASE: todo
    secrets:
      - mongo_root_user
      - mongo_root_pass
      - mongo_db_user
      - mongo_db_pass

secrets:
  mongo_root_user:
    file: ./mongo/secrets/root_user.secret
  mongo_root_pass:
    file: ./mongo/secrets/root_pass.secret
  mongo_db_user:
    file: ./mongo/secrets/db_user.secret
  mongo_db_pass:
    file: ./mongo/secrets/db_pass.secret
